bind 127.0.0.1
protected-mode yes
port 6379

dir /var/lib/redis-receipt-whatsapp-bot
dbfilename dump.rdb

save 900 1
save 300 10
save 60 10000

appendonly yes
appendfilename appendonly.aof
appendfsync everysec

stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes

tcp-keepalive 300
timeout 0

maxmemory 512mb
maxmemory-policy noeviction

daemonize no
supervised systemd
