const {
  RECEIPT_FIELD_KEYS,
  REQUIRED_FIELD_ORDER,
} = require('../shared');

module.exports = {
  id: 'mar_e_rio',
  company: {
    code: 'mar_e_rio',
    displayName: 'MAR E RIO',
  },
  invoiceLookup: {
    companyCode: 'mar_e_rio',
  },
  template: {
    id: 'mar_e_rio_receipt_v1',
    label: 'Canhoto padrao MAR E RIO',
    standardWidth: 1800,
    aspectRatio: 8.9,
    minAspectRatio: 5.2,
    maxAspectRatio: 13.5,
    minTemplateScore: 58,
  },
  requiredFieldOrder: REQUIRED_FIELD_ORDER.slice(),
  fieldSpecs: {
    [RECEIPT_FIELD_KEYS.dataRecebimento]: {
      key: RECEIPT_FIELD_KEYS.dataRecebimento,
      label: 'DATA DE RECEBIMENTO',
      aliases: [
        'data de recebimento',
        'data recebimento',
        'data do recebimento',
        'dt recebimento',
      ],
      expectedRegionIds: ['roi_date_label', 'roi_document_support', 'global_support'],
      acceptanceThreshold: 0.66,
    },
    [RECEIPT_FIELD_KEYS.issuerHeader]: {
      key: RECEIPT_FIELD_KEYS.issuerHeader,
      label: 'RECEBEMOS DE MAR E RIO',
      aliases: [
        'recebemos de mar e rio',
        'recebemos da mar e rio',
        'recebemos mar e rio',
        'mar e rio pescados',
        'mar e rio pescados ind imp exp',
        'marerio pescados',
        'recebemos de marerio',
        'recebemos da marerio',
      ],
      expectedRegionIds: ['roi_header', 'roi_document_support', 'global_support'],
      acceptanceThreshold: 0.62,
    },
    [RECEIPT_FIELD_KEYS.nfe]: {
      key: RECEIPT_FIELD_KEYS.nfe,
      label: 'NF-e',
      aliases: [
        'nf e',
        'nf-e',
        'nfe',
        'nota fiscal',
        'nota fiscal eletronica',
        'serie',
        'numero',
      ],
      expectedRegionIds: ['roi_nf_block', 'roi_nf_number_line', 'global_support'],
      acceptanceThreshold: 0.68,
    },
  },
  templateRoiDefinitions: [
    {
      id: 'roi_document_support',
      label: 'Documento alinhado mascarado',
      role: 'document_support',
      box: { x: 0.0, y: 0.0, width: 1.0, height: 1.0 },
    },
    {
      id: 'roi_header',
      label: 'Cabecalho do emissor',
      role: 'header',
      box: { x: 0.12, y: 0.04, width: 0.71, height: 0.31 },
    },
    {
      id: 'roi_date_label',
      label: 'Campo DATA DE RECEBIMENTO',
      role: 'date_label',
      box: { x: 0.005, y: 0.35, width: 0.17, height: 0.34 },
    },
    {
      id: 'roi_nf_block',
      label: 'Bloco NF-e',
      role: 'nf_block',
      box: { x: 0.84, y: 0.02, width: 0.155, height: 0.92 },
    },
    {
      id: 'roi_nf_header',
      label: 'Topo do bloco NF-e',
      role: 'nf_header',
      box: { x: 0.855, y: 0.03, width: 0.13, height: 0.22 },
    },
    {
      id: 'roi_nf_number_line',
      label: 'Linha do numero da NF-e',
      role: 'nf_number_line',
      box: { x: 0.855, y: 0.22, width: 0.13, height: 0.24 },
    },
    {
      id: 'roi_nf_number_tight',
      label: 'Numero da NF-e apertado',
      role: 'nf_number_tight',
      box: { x: 0.89, y: 0.22, width: 0.1, height: 0.2 },
    },
    {
      id: 'roi_nf_series_line',
      label: 'Linha de serie do bloco NF-e',
      role: 'nf_series',
      box: { x: 0.855, y: 0.47, width: 0.13, height: 0.2 },
    },
    {
      id: 'roi_signature',
      label: 'Area de assinatura e identificacao',
      role: 'signature',
      ignoreForOcr: true,
      box: { x: 0.18, y: 0.35, width: 0.66, height: 0.46 },
    },
  ],
  analysisRegionDefinitions: [
    {
      id: 'roi_header',
      label: 'Cabecalho do emissor',
      box: { x: 0.12, y: 0.04, width: 0.71, height: 0.31 },
      fieldKeys: [RECEIPT_FIELD_KEYS.issuerHeader],
    },
    {
      id: 'roi_date_label',
      label: 'Campo DATA DE RECEBIMENTO',
      box: { x: 0.005, y: 0.35, width: 0.17, height: 0.34 },
      fieldKeys: [RECEIPT_FIELD_KEYS.dataRecebimento],
    },
    {
      id: 'roi_nf_block',
      label: 'Bloco NF-e',
      box: { x: 0.84, y: 0.02, width: 0.155, height: 0.92 },
      fieldKeys: [RECEIPT_FIELD_KEYS.nfe],
    },
    {
      id: 'roi_nf_number_line',
      label: 'Linha do numero da NF',
      box: { x: 0.855, y: 0.22, width: 0.13, height: 0.24 },
      fieldKeys: [RECEIPT_FIELD_KEYS.nfe],
    },
  ],
  orientationProbeRegionDefinitions: [
    {
      id: 'roi_header',
      label: 'Cabecalho do emissor',
      box: { x: 0.12, y: 0.04, width: 0.71, height: 0.31 },
      fieldKeys: [RECEIPT_FIELD_KEYS.issuerHeader],
    },
    {
      id: 'roi_date_label',
      label: 'Campo DATA DE RECEBIMENTO',
      box: { x: 0.005, y: 0.35, width: 0.17, height: 0.34 },
      fieldKeys: [RECEIPT_FIELD_KEYS.dataRecebimento],
    },
    {
      id: 'roi_nf_block',
      label: 'Bloco NF-e',
      box: { x: 0.84, y: 0.02, width: 0.155, height: 0.92 },
      fieldKeys: [RECEIPT_FIELD_KEYS.nfe],
    },
  ],
  nfRoiDefinitions: [
    {
      id: 'nf_block',
      label: 'Bloco NF-e',
      box: { x: 0.84, y: 0.02, width: 0.155, height: 0.92 },
      phase: 'primary',
      minWidth: 140,
      minHeight: 60,
      fallbackRoiId: 'nf_block_wide',
    },
    {
      id: 'nf_number_line',
      label: 'Linha do numero da NF',
      box: { x: 0.855, y: 0.22, width: 0.13, height: 0.24 },
      phase: 'primary',
      minWidth: 110,
      minHeight: 36,
      fallbackRoiId: 'nf_block',
    },
    {
      id: 'nf_number_tight',
      label: 'Numero da NF apertado',
      box: { x: 0.89, y: 0.22, width: 0.1, height: 0.2 },
      phase: 'primary',
      minWidth: 84,
      minHeight: 28,
      fallbackRoiId: 'nf_number_line',
    },
    {
      id: 'nf_header',
      label: 'Cabecalho do bloco NF-e',
      box: { x: 0.855, y: 0.03, width: 0.13, height: 0.22 },
      phase: 'primary',
      minWidth: 110,
      minHeight: 36,
      fallbackRoiId: 'nf_block',
    },
    {
      id: 'nf_block_wide',
      label: 'Bloco NF-e expandido',
      box: { x: 0.8, y: 0.0, width: 0.2, height: 0.98 },
      phase: 'fallback',
      minWidth: 180,
      minHeight: 60,
      fallbackRoiId: null,
    },
  ],
};
